# Gridworld

###

![Gridworld](imgs/Q1_Gridworld.PNG)

In [8]:
import numpy as np

Givens:

$\gamma=1$

$r_s\in \{-1, 0, 1\}$

$r_{5} = -5$

$r_{12} = 5$

In [9]:
gamma = 1

![a)](imgs/Q1_a.PNG)
### a)

$r_s >= 0$ will not necessarily find the shortest path.  $r_s < 0$ will.

Optimal value of state 1 = $r_t + \gamma r_{(t+1)} + \gamma^2 r_{(t+2)} + ...$

In [10]:
R = np.zeros((16, 1)) - 1
R[11] = 5
R[4] = -5

One set of transitions which will return the shortest path are:

In [11]:
P = np.zeros((16,16))
P[0, 1] = 1
P[1, 2] = 1
P[2, 3] = 1
P[3, 7] = 1
# P[4, 1] = 1
P[5, 6] = 1
P[6, 7] = 1
P[7, 11] = 1
P[8, 9] = 1
P[9, 10] = 1
P[10, 11] = 1
# P[11, ]
P[12, 8] = 1
P[13, 12] = 1
P[14, 13] = 1
P[15, 14] = 1

In [13]:
V = np.matmul(np.linalg.inv(np.eye(16) - gamma * P), R)

In [15]:
V.reshape((4,4))  # Reshaped to the gridworld for easier viewing 

array([[ 0.,  1.,  2.,  3.],
       [-5.,  2.,  3.,  4.],
       [ 2.,  3.,  4.,  5.],
       [ 1.,  0., -1., -2.]])

![b)](imgs/Q1_b.PNG)
### b)

In [16]:
R += 2

In [17]:
R

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-3.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 7.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [18]:
V = np.matmul(np.linalg.inv(np.eye(16) - gamma * P), R)

In [21]:
V.reshape((4,4))

array([[12., 11., 10.,  9.],
       [-3., 10.,  9.,  8.],
       [10.,  9.,  8.,  7.],
       [11., 12., 13., 14.]])

![c)](imgs/Q1_c.PNG)
### c)

Old value is the discounted sum of future rewards

$V_{old}^\pi=\mathbb{E}_\pi\left[\sum_{T=0}^{\infty}\gamma^Tr_{t+T}|s_t=s\right]$

New value is the old value + constant

$V_{new}^\pi=\mathbb{E}_\pi\left[\sum_{T=0}^{\infty}\gamma^T\left(r_{t+T}+c\right)|s_t=s\right]$

$V_{new}^\pi=\mathbb{E}_\pi\left[\sum_{T=0}^{\infty}\gamma^Tr_{t+T}+\gamma^Tc|s_t=s\right]$

$V_{new}^\pi=\mathbb{E}_\pi\left[\sum_{T=0}^{\infty}\gamma^Tr_{t+T}|s_t=s\right] + \sum_{T=0}^{\infty}\gamma^Tc$

For $\gamma < 1$, the infinite sum is equal to $c/(1-\gamma)$

$V_{new}^\pi=V_{old} + \frac{c}{1-\gamma}$

Note, for our example above, gamma did not fit that infinite sum criteria

![d)](imgs/Q1_d.PNG)
### d)

In [22]:
V.reshape((4,4))

array([[12., 11., 10.,  9.],
       [-3., 10.,  9.,  8.],
       [10.,  9.,  8.,  7.],
       [11., 12., 13., 14.]])

Because an agent would receive positive rewards in many states, for an infinite horizon problem, the agent would move around randomly while avoiding the states with terminal conditions.  The value of the unshaded squares will approach $+\infty$.

![e)](imgs/Q1_e.PNG)
### e)

For very small values of $\gamma$, the immediate rewards become much more important.  This may result in non infinite values because the agent may prioritize getting to a terminal state rather than spend infinite time collecting small rewards.  IE. the agent might get 'tricked' into thinkin gthat large immediate rewards is better than infinite small rewards

![f)](imgs/Q1_f.PNG)
### f)

The furthest from the $r_g$ while closest to $r_r$ is 3 steps, for $\gamma=1$, the equivalent value will be when $r_r + r_s = 3r_s + r_g$ or $-5 + r_s = 3r_s + 5$ or $r_s = -5$

Therefore, if $r_s<-5$, there will be an optimal policy which terminates at the red shaded area and if $r_s=-5$ then an optimal policy could terminate at the red shaded area or the green shaded area for an agent in square {6, 10, 9, 13, 14, 15, 16}.